import streamlit as st
import pandas as pd
import joblib

# --- PAGE CONFIGURATION ---
st.set_page_config(page_title="AI Car Valuation", page_icon="🚗", layout="centered")


# --- LOAD AI MODEL ---
@st.cache_resource
def load_model():
    try:
        model = joblib.load("car_valuation_model.pkl")
        model_columns = joblib.load("model_columns.pkl")
        return model, model_columns
    except FileNotFoundError:
        return None, None


model, model_columns = load_model()

# --- HEADER ---
st.title("🚗 AI-Powered Car Valuation")
st.markdown(
    "Enter the vehicle details below to get an instant, machine learning-driven price estimate based on global market trends.")
st.markdown("---")

if model is None:
    st.error("⚠️ Model files not found! Please run 'model_trainer.py' first.")
else:
    # --- USER INPUT FORM ---
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Vehicle Specifications")
        brand = st.selectbox("Brand & Model",
                             ["Toyota Corolla", "Honda Civic", "Ford Focus", "BMW 3 Series", "Volkswagen Golf",
                              "Fiat Tipo", "Tesla Model 3"])
        year = st.slider("Manufacturing Year", 2015, 2024, 2020)
        color = st.selectbox("Color", ["White", "Black", "Gray", "Red", "Blue"])
        horsepower = st.number_input("Horsepower (HP)", min_value=90, max_value=400, value=150, step=10)

    with col2:
        st.subheader("Condition & History")
        mileage = st.number_input("Mileage (Miles)", min_value=0, max_value=300000, value=45000, step=1000)
        transmission = st.selectbox("Transmission", ["Automatic", "Manual"])
        condition = st.selectbox("Vehicle Condition", ["Clean Title", "Minor Scratches", "Repaired", "Salvage"])

    st.markdown("---")

    # --- PREDICTION LOGIC ---
    if st.button("🔮 Estimate Market Price", use_container_width=True):
        with st.spinner("AI is analyzing market data..."):
            # Create a dataframe from user inputs
            input_data = pd.DataFrame([{
                "Brand": brand, "Year": year, "Mileage": mileage,
                "Transmission": transmission, "Horsepower": horsepower,
                "Condition": condition, "Color": color
            }])

            # Preprocess the input the same way we trained the model
            input_encoded = pd.get_dummies(input_data)

            # Align the input columns with the model's trained columns
            input_aligned = input_encoded.reindex(columns=model_columns, fill_value=0)

            # Make the prediction
            predicted_price = model.predict(input_aligned)[0]

            # Display Result
            st.success("Analysis Complete!")
            st.metric(label="Estimated Fair Market Value", value=f"${predicted_price:,.0f}")
            st.info("ℹ️ This valuation is generated by a Random Forest Machine Learning model.")